conda activate deneme_env
python training_scripts/train_cls_bayes.py
python training_scripts/train_cls_dt.py
python training_scripts/train_cls_knn.py
python training_scripts/train_cls_svm.py
python training_scripts/train_reg_dt.py
python training_scripts/train_reg_knn.py
python training_scripts/train_reg_lr.py
python training_scripts/train_reg_pr.py